# Generated by Django 4.2.3 on 2023-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, max_length=50, null=True)),
                ('questionid', models.IntegerField(blank=True, max_length=50, null=True)),
                ('answerid', models.IntegerField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField(max_length=5000)),
                ('likescount', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=500)),
                ('question', models.TextField(max_length=5000)),
                ('questionid', models.IntegerField(blank=True, max_length=50, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('token', models.CharField(blank=True, max_length=40, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
