# Generated by Django 4.2.3 on 2023-07-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('token', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
