# Generated by Django 4.2.3 on 2023-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_userinformation_profileimgurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdetails',
            name='answerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerdetails',
            name='questionid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerdetails',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiondetails',
            name='questionid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiondetails',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
