# Generated by Django 4.2.3 on 2023-07-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_userinformation_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('questionid', models.CharField(blank=True, max_length=50, null=True)),
                ('answerid', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField(max_length=5000)),
                ('likescount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=500)),
                ('question', models.TextField(max_length=5000)),
                ('questionid', models.CharField(blank=True, max_length=50, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinformation',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
