# Generated by Django 4.2.3 on 2023-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_answerdetails_answerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
