# Generated by Django 4.2.3 on 2023-07-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_answerdetails_questiondetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdetails',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
