# Generated by Django 4.2.3 on 2023-07-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_answerdetails_answerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdetails',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
